# Generated by Django 3.2.6 on 2021-08-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210824_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollageMaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='CollageMaking/')),
            ],
        ),
        migrations.CreateModel(
            name='Electroinsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=200)),
                ('teamname', models.CharField(default=' ', max_length=200)),
                ('name1', models.CharField(default=' ', max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.BigIntegerField()),
                ('branch1', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='Electroinsight/')),
                ('name2', models.CharField(default=' ', max_length=20)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.BigIntegerField()),
                ('branch2', models.CharField(default=' ', max_length=50)),
                ('id2', models.FileField(blank=True, null=True, upload_to='Electroinsight/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=200)),
                ('teamname', models.CharField(default=' ', max_length=200)),
                ('name1', models.CharField(default=' ', max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.BigIntegerField()),
                ('branch1', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='ProjectDisplay/')),
                ('name2', models.CharField(default=' ', max_length=20)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.BigIntegerField()),
                ('branch2', models.CharField(default=' ', max_length=50)),
                ('id2', models.FileField(blank=True, null=True, upload_to='ProjectDisplay/')),
            ],
        ),
        migrations.CreateModel(
            name='Rangoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=200)),
                ('teamname', models.CharField(default=' ', max_length=200)),
                ('name1', models.CharField(default=' ', max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.BigIntegerField()),
                ('branch1', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='Rangoli/')),
                ('name2', models.CharField(default=' ', max_length=20)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone2', models.BigIntegerField(blank=True, null=True)),
                ('branch2', models.CharField(default=' ', max_length=50)),
                ('id2', models.FileField(blank=True, null=True, upload_to='Rangoli/')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalPresentationCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='TechnicalPresentationCSE/')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalPresentationEce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='TechnicalPresentationEce/')),
            ],
        ),
        migrations.CreateModel(
            name='TechQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default=' ', max_length=50)),
                ('id1', models.FileField(upload_to='TechQuiz/')),
            ],
        ),
    ]
