# Generated by Django 3.2.6 on 2021-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210824_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakthestrategy',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='collagemaking',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='designathon',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='electroinsight',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='projectdisplay',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='rangoli',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalpresentation',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
        migrations.AddField(
            model_name='techquiz',
            name='type_institution',
            field=models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20),
        ),
    ]
