# Generated by Django 3.2.6 on 2021-08-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakthestrategy',
            old_name='branch',
            new_name='branch_class',
        ),
        migrations.RenameField(
            model_name='breakthestrategy',
            old_name='college',
            new_name='college_school',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
