# Generated by Django 3.2.6 on 2021-08-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210825_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakthestrategy',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakthestrategy',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
