# Generated by Django 3.2.6 on 2021-08-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210825_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collagemaking',
            old_name='branch',
            new_name='branch_class',
        ),
        migrations.RenameField(
            model_name='collagemaking',
            old_name='college',
            new_name='college_school',
        ),
        migrations.RenameField(
            model_name='technicalpresentation',
            old_name='branch',
            new_name='branch_class',
        ),
        migrations.RenameField(
            model_name='technicalpresentation',
            old_name='college',
            new_name='college_school',
        ),
        migrations.RenameField(
            model_name='techquiz',
            old_name='branch',
            new_name='branch_class',
        ),
        migrations.RenameField(
            model_name='techquiz',
            old_name='college',
            new_name='college_school',
        ),
        migrations.AddField(
            model_name='collagemaking',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collagemaking',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalpresentation',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalpresentation',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techquiz',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techquiz',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
