# Generated by Django 3.2.6 on 2021-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210825_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakthestrategy',
            name='id1',
            field=models.ImageField(upload_to='BreakTheStrategy/'),
        ),
    ]
