# Generated by Django 3.2.6 on 2021-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_breakthestrategy_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='designathon',
            name='rollno1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='rollno2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='rollno3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='rollno4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='semester1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='semester2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='semester3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designathon',
            name='semester4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
