# Generated by Django 3.2.6 on 2021-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210826_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboPresetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20)),
                ('college', models.CharField(default='', max_length=200)),
                ('teamname', models.CharField(default=' ', max_length=200)),
                ('name1', models.CharField(default=' ', max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.BigIntegerField()),
                ('branch1', models.CharField(default=' ', max_length=50)),
                ('semester1', models.IntegerField(blank=True, null=True)),
                ('rollno1', models.BigIntegerField(blank=True, null=True)),
                ('id1', models.FileField(upload_to='RoboPresentation/')),
                ('name2', models.CharField(default=' ', max_length=20)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.BigIntegerField()),
                ('branch2', models.CharField(default=' ', max_length=50)),
                ('semester2', models.IntegerField(blank=True, null=True)),
                ('rollno2', models.BigIntegerField(blank=True, null=True)),
                ('id2', models.FileField(blank=True, null=True, upload_to='RoboPresentation/')),
                ('name3', models.CharField(default=' ', max_length=20)),
                ('email3', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone3', models.BigIntegerField(blank=True, null=True)),
                ('branch3', models.CharField(default=' ', max_length=50)),
                ('semester3', models.IntegerField(blank=True, null=True)),
                ('rollno3', models.BigIntegerField(blank=True, null=True)),
                ('id3', models.FileField(blank=True, null=True, upload_to='RoboPresentation/')),
            ],
        ),
    ]
