# Generated by Django 3.2.6 on 2021-08-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_robopresetation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangoli',
            name='branch2',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='name2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='teamname',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
