# Generated by Django 3.2.6 on 2021-08-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210827_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangoli',
            name='rollno1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rangoli',
            name='rollno2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
