# Generated by Django 3.2.6 on 2021-08-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210827_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rangoli',
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='email1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
