# Generated by Django 3.2.6 on 2021-08-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210827_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rangoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20)),
                ('college', models.CharField(default='', max_length=200)),
                ('teamname', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('name1', models.CharField(default=' ', max_length=20)),
                ('email1', models.EmailField(default=' ', max_length=254)),
                ('phone1', models.BigIntegerField()),
                ('branch1', models.CharField(default=' ', max_length=50)),
                ('semester1', models.IntegerField(blank=True, null=True)),
                ('rollno1', models.BigIntegerField(blank=True, null=True)),
                ('id1', models.FileField(upload_to='Rangoli/')),
                ('name2', models.CharField(default=' ', max_length=20)),
                ('email2', models.EmailField(default=' ', max_length=254)),
                ('phone2', models.BigIntegerField()),
                ('branch2', models.CharField(default=' ', max_length=50)),
                ('semester2', models.IntegerField(blank=True, null=True)),
                ('rollno2', models.BigIntegerField(blank=True, null=True)),
                ('id2', models.FileField(blank=True, null=True, upload_to='Rangoli/')),
            ],
        ),
    ]
