# Generated by Django 3.2.6 on 2021-08-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rangoli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robopresetation',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='rollno3',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='robopresetation',
            name='semester3',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
