# Generated by Django 3.2.6 on 2021-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210828_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangoli',
            name='email1',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='email2',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='rangoli',
            name='teamname',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
