# Generated by Django 3.2.6 on 2021-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210828_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroinsight',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electroinsight',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electroinsight',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='electroinsight',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='id1',
            field=models.FileField(upload_to='RoboPresentation/'),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='phone4',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='rollno3',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='rollno4',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='semester3',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='designathon',
            name='semester4',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='electroinsight',
            name='id1',
            field=models.FileField(upload_to='ArduinoChallenge/'),
        ),
        migrations.AlterField(
            model_name='electroinsight',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='ArduinoChallenge/'),
        ),
        migrations.AlterField(
            model_name='electroinsight',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='electroinsight',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
