# Generated by Django 3.2.6 on 2021-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20210828_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdisplay',
            name='projectname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdisplay',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectdisplay',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectdisplay',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='projectdisplay',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='email1',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='email2',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='id1',
            field=models.FileField(upload_to='Rangoli/'),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='Rangoli/'),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
