# Generated by Django 3.1.5 on 2021-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20210902_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rangoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_institution', models.CharField(choices=[('college', 'college'), ('school', 'school')], default='college', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college_school', models.CharField(default='', max_length=200)),
                ('branch_class', models.CharField(default=' ', max_length=50)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('id1', models.FileField(upload_to='Rangoli/')),
            ],
        ),
    ]
