# Generated by Django 3.1.5 on 2021-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_rangoli'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electroinsight',
            new_name='ArdunioPiChallenge',
        ),
    ]
