# Generated by Django 3.1.5 on 2021-09-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210905_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakTheStrategy',
            new_name='CGCCODATHON',
        ),
    ]
