# Generated by Django 3.1.5 on 2021-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_autocad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiworkshop',
            name='id1',
            field=models.FileField(upload_to='CGCCODATHON/'),
        ),
    ]
