# Generated by Django 3.1.5 on 2021-09-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_cecjinovationidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyberworkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college_school', models.CharField(default='', max_length=200)),
                ('id1', models.FileField(upload_to='Cyberworkshop/')),
            ],
        ),
    ]
