# Generated by Django 4.1 on 2022-09-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_projectdisplay_branch3_projectdisplay_branch4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aiworkshop',
        ),
        migrations.DeleteModel(
            name='ArdunioPiChallenge',
        ),
        migrations.DeleteModel(
            name='CECJHACKATHON',
        ),
        migrations.DeleteModel(
            name='CecJInovationidea',
        ),
        migrations.DeleteModel(
            name='CollageMaking',
        ),
        migrations.DeleteModel(
            name='Cyberworkshop',
        ),
        migrations.DeleteModel(
            name='EmailPool',
        ),
        migrations.DeleteModel(
            name='RoboPresetation',
        ),
    ]
