# Generated by Django 4.1 on 2022-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_techcharades_branch2_techcharades_email2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcharades',
            name='teamname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
