# Generated by Django 4.1 on 2022-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_technicalquizce_branch2_technicalquizce_email2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalcollage',
            old_name='branch_class',
            new_name='branch1',
        ),
        migrations.RenameField(
            model_name='technicalcollage',
            old_name='college_school',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='technicalcollage',
            old_name='email',
            new_name='email1',
        ),
        migrations.RemoveField(
            model_name='technicalcollage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technicalcollage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='technicalcollage',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='technicalcollage',
            name='semester',
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='branch2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='branch3',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='email3',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='TechnicalCollage/'),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='id3',
            field=models.FileField(blank=True, null=True, upload_to='TechnicalCollage/'),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='name1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='name2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='name3',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='phone3',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='projectname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='rollno3',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='semester3',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='technicalcollage',
            name='teamname',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
