# Generated by Django 4.1 on 2022-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_rename_branch_class_technicalcollage_branch1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalCollage',
        ),
    ]
