# Generated by Django 4.1 on 2022-09-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_technicalcollage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalcollage',
            name='projectname',
        ),
    ]
