# Generated by Django 4.1 on 2022-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_alter_surveyscout_id3_alter_surveyscout_id4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rangoli',
        ),
        migrations.RenameField(
            model_name='floatingconcreteboat',
            old_name='branch_class',
            new_name='branch5',
        ),
        migrations.RenameField(
            model_name='floatingconcreteboat',
            old_name='college_school',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='floatingconcreteboat',
            old_name='email',
            new_name='email1',
        ),
        migrations.RemoveField(
            model_name='floatingconcreteboat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='floatingconcreteboat',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='floatingconcreteboat',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='floatingconcreteboat',
            name='semester',
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='branch1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='branch2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='branch3',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='branch4',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='email3',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='email4',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='email5',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='FloatingConcreteBoat/'),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='id3',
            field=models.FileField(blank=True, null=True, upload_to='FloatingConcreteBoat/'),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='id4',
            field=models.FileField(blank=True, null=True, upload_to='FloatingConcreteBoat/'),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='id5',
            field=models.FileField(blank=True, null=True, upload_to='FloatingConcreteBoat/'),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='name1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='name2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='name3',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='name4',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='name5',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='phone3',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='phone4',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='phone5',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='rollno3',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='rollno4',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='rollno5',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='semester3',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='semester4',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='semester5',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='floatingconcreteboat',
            name='teamname',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='id1',
            field=models.FileField(upload_to='ProjectDisplay/'),
        ),
        migrations.AlterField(
            model_name='projectdisplay',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='ProjectDisplay/'),
        ),
    ]
