# Generated by Django 4.1 on 2022-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_delete_rangoli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='branch2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='bplan',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bplan',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='Bplan/'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='name2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='bplan',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='bplan',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bplan',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bplan',
            name='teamname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
