# Generated by Django 4.1 on 2022-09-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_surveyscout_email1_alter_surveyscout_email2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechrelay',
            old_name='branch_class',
            new_name='branch1',
        ),
        migrations.RenameField(
            model_name='mechrelay',
            old_name='college_school',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='mechrelay',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mechrelay',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mechrelay',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mechrelay',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='mechrelay',
            name='semester',
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='branch2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='branch3',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='branch4',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='email1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='email3',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='email4',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='id2',
            field=models.FileField(blank=True, null=True, upload_to='Mechrelay/'),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='id3',
            field=models.FileField(blank=True, null=True, upload_to='Mechrelay/'),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='id4',
            field=models.FileField(blank=True, null=True, upload_to='Mechrelay/'),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='name1',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='name2',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='name3',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='name4',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='phone1',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='phone2',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='phone3',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='phone4',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='projectname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='rollno1',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='rollno2',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='rollno3',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='rollno4',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='semester1',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='semester2',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='semester3',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='semester4',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mechrelay',
            name='teamname',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
