# Generated by Django 4.1 on 2022-09-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_rename_branch_class_mechrelay_branch1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechrelay',
            name='projectname',
        ),
    ]
