# Generated by Django 4.1 on 2022-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_rename_branch_class_robolympics_branch1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robolympics',
            name='eventype',
            field=models.CharField(default='', max_length=200),
        ),
    ]
