# Generated by Django 4.1 on 2022-09-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_robolympics_eventype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robolympics',
            name='projectname',
        ),
    ]
